nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['https://tpv.fajasmaylu.com']  # Cambia esto por el dominio de tu frontend
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/':  # Aplica CORS a todas las rutas
      allow_origin: ['https://tpv.fajasmaylu.com']