<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240504120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop location column from ps_product_attribute table';
    }

    public function up(Schema $schema): void
    {
        // this migration is autogenerated, please modify to your needs
        $this->addSql('ALTER TABLE ps_product_attribute DROP COLUMN location');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ps_product_attribute ADD location VARCHAR(64) DEFAULT NULL');
    }
}
